[project]
name = "sylvan-agro-certification-hub"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/sylvan-agro-certification-hub/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.sylvan-agro-certification-hub]
path = "contracts/sylvan-agro-certification-hub.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
